### ISSUE TITLE
翻译无法使用

### ISSUE THREAD

**Issue by yunkuangao** [ybw2016v/mkts#1]
脚本还是2021年的，现在的misskey版本已经无法使用了，可以麻烦作者更新一下吗。

**Comment by ybw2016v** [comment]
最近比较忙，可能要过一小段时间再解决这个问题了……

**Comment by yunkuangao** [comment]
好的，大佬有时间搞就行了，这个问题我就先不关闭了，谢谢大佬。 😄

**Comment by ybw2016v** [comment]
更新完了 @yunkuangao

**Comment by yunkuangao** [comment]
谢谢更新，我在使用的时候，服务端这边报了个错误
```
[2023-05-04 10:57:28,426] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/api.py", line 75, in post
    r = dog_rs_fy(c, t, 0)
  File "/app/api.py", line 49, in dog_rs_fy
    rr_dog = dog_rd_ts(c, t)
  File "/app/api.py", line 31, in dog_rd_ts
    res=ts.translate_text(indog,translator=rs,to_language=todog)
AttributeError: module 'translators' has no attribute 'translate_text'
```

我对python不是很熟悉，麻烦作者帮忙看看这个错误是什么原因造成的，再次感谢

**Comment by ybw2016v** [comment]
翻译后端所依赖的translators版本变了，更新一下就好了

```
pip install --upgrade translators
```

@yunkuangao

**Comment by yunkuangao** [comment]
可以正常运行了，谢谢作者大大。❤️
